In [1]:
import pandas as pd
from pprint import pprint
import re
import numpy as np

pd.set_option('display.max_rows', None)

In [2]:
!mkdir -p tables

In [3]:
def load_results(filename, roundat=2):
    results = pd.read_pickle(filename)
    results['batch_size']=results.train_params.str.extract(".*batch_size=([0-9]+).*")
    results['learning_rate']=results.train_params.str.extract(".*learning_rate=(.+?),.*")
    print("Number of results so far: ", len(results))

    results['f1_test'] = results.f1_test.round(roundat)
    results['PER_f1_test'] = results.PER_f1_test.round(roundat)
    results['LOC_f1_test'] = results.LOC_f1_test.round(roundat)
    results['ORG_f1_test'] = results.ORG_f1_test.round(roundat)

    return results

In [4]:
#Make a nice table.

def merge_historical_results(rsingle, rzefys, rall):
    _res_single = rsingle
    _res_pretrained_zefys = rzefys.drop(columns=['pretrain'])
    _res_pretrained_all = rall.drop(columns=['pretrain'])
    
    merged_results = _res_single.merge(_res_pretrained_zefys, on=['train', 'test','model'], suffixes=['','_PZ'], how='outer')
    merged_results = merged_results.merge(_res_pretrained_all, on=['train', 'test','model'], suffixes=['','_PA'], how='outer')

    tmp = pd.concat([rsingle, rzefys, rall])

    per_loc_org=[]
    for _, res in tmp.groupby(['train', 'test', 'model']):
        per_loc_org.append(res.sort_values('f1_test', ascending=False).iloc[[0]])

    per_loc_org=pd.concat(per_loc_org).rename(columns={'PER_f1_test': 'PER_f1_best', 'LOC_f1_test': 'LOC_f1_best', 'ORG_f1_test': 'ORG_f1_best'})

    print(per_loc_org.columns)
    
    per_loc_org=per_loc_org[['train', 'test','model', 'PER_f1_best', 'LOC_f1_best', 'ORG_f1_best']]

    merged_results = merged_results.merge(per_loc_org, on=['train', 'test','model'])

    return merged_results

def make_nice_table(df_input, dataset_order, use_columns, max_columns, dataset_column='test', additional_columns=['dataset', 'model']):
    
    atab = df_input.copy()
    
    atab['max_f1'] = atab[max_columns].apply(lambda x: x.mean(), axis=1)
    atab = atab.sort_values(['test', 'max_f1'], ascending=[False,False])
    
    atab['dataset'] = atab[dataset_column] 
    
    atab = pd.concat([atab.loc[atab.dataset==o] for o in dataset_order]).reset_index(drop=True)

    def model_rename(x):
        if x=="electra-base-german-europeana-cased-discriminator":
            return "Europ-Electra"            
            
        if x=="bert-base-historic-multilingual-cased":
            return "hmBERT"            
                        
        if x=="bert-tiny-historic-multilingual-cased":
            return "hmBERT-tiny"            
                        
        if x=="bert-mini-historic-multilingual-cased":
            return "hmBERT-mini"            
                        
        if x=="bert-base-german-cased":
            return "GermanBERT"            
                        
        if x=="roberta-base":
            return "Roberta"            
                        
        if x=="xlm-roberta-base":
            return "XLM-Roberta"            
                        
        if x=="gbert-base":
            return "GBERT"            
                        
        if x=="distilbert-base-uncased":
            return "Distilbert"            
                        
    
    atab['model'] = atab['model'].apply(model_rename)
    
    #def abbreviate(x):
    #    return "".join([p[0] for p in x.split('-')]).upper()
    # 
    #atab['model'] = atab['model'].apply(abbreviate)
    
    def dataset_rename(x):
    
        if x=="zefys2025":
            return "Anon2025"
    
        if x=="hipe2020":
            return "HIPE 2020"
    
        if x=="hisgerman":
            return "HisGermanNER"
    
        if x=="europeana-onb":
            return "Europeana-ÖNB"
    
        if x=="europeana-lft":
            return "Europeana-LFT"
    
        if x=="neiss-arendt":
            return "Neiss-Arendt"
    
        if x=="neiss-sturm":
            return "Neiss-Sturm"

        if x=='conll2003':
            return "CoNLL-2003"
            
        if x=='germeval_14':
            return "GermEval2014"
        
        return x
    
    atab['dataset'] = atab['dataset'].apply(dataset_rename)
    atab[dataset_column] = atab[dataset_column].apply(dataset_rename)
    atab['test'] = atab['test'].apply(dataset_rename)
    
    atab = atab[additional_columns + use_columns]

    btab=[]
    for dataset, part in atab.groupby('dataset', sort=False):

        part = part.drop(columns=['dataset'])
        btab.append(pd.concat([pd.DataFrame([("__" + dataset + "__",) + (part.shape[1]-1)*(np.nan,)], columns=part.columns), part],));

    btab = pd.concat(btab).reset_index(drop=True)
    
    nice_table = btab.style.\
        highlight_max(axis = 1, subset=max_columns, props='font-weight:bold').\
        format('{:.2f}', na_rep='-', subset=use_columns).\
        hide(axis='index')

    return nice_table, btab


def write_to_latex_file(nice_table, filename, num_cols):
    tex_code = nice_table.to_latex(hrules=True)

    tex_code = tex_code.replace("\\font-weightbold", "\\bf")

    tex_code = re.sub(r".*__(.*?)__.*", r"\\multicolumn{" + str(num_cols) + r"}{c}{\1} \\\\", tex_code)

    
    tex_code = re.sub(r"([^\s]*_[^\s]*)", r"$\1$", tex_code)
    tex_code = re.sub(r"_([^\s^_^$]*)", r"_{\1}", tex_code)
    
    with open(filename, 'w') as f:
        f.write(tex_code)

    return tex_code

# Contemporary

In [5]:
atab = []
for dataset, res in load_results('experiments/results-single.pkl').groupby(['train', 'test', 'model']):
    atab.append(res.sort_values('f1_test', ascending=False).iloc[[0]])
atab = pd.concat(atab).sort_values(['test','f1_early'], ascending=[True, False]).reset_index(drop=True)
atab = atab.loc[atab.train==atab.test]

test_val_diff = (atab['f1_test'] - atab['f1_early']).abs()
print('Average distance between early stopping f_1-score and test f_1-score: {}+-{}'.\
      format(test_val_diff.mean().round(2), test_val_diff.std().round(2)))

contemp_table, df_contemp = make_nice_table(atab,dataset_order=['conll2003', 'GermEval'], 
                                            use_columns=['f1_test', 'f1_early' , 'PER_f1_test', 'LOC_f1_test', 'ORG_f1_test'], max_columns=[])
contemp_table

Number of results so far:  6597
Average distance between early stopping f_1-score and test f_1-score: 0.02+-0.02

In [6]:
write_to_latex_file(contemp_table,'tables/contemporary.tex', df_contemp.shape[1])

'\\begin{tabular}{lrrrrr}\n\\toprule\nmodel & $f1_{test}$ & $f1_{early}$ & $PER_{f1}_{test}$ & $LOC_{f1}_{test}$ & $ORG_{f1}_{test}$ \\\\\n\\midrule\n\\multicolumn{6}{c}{CoNLL-2003} \\\\\nRoberta & 0.94 & 0.97 & 0.96 & 0.93 & 0.92 \\\\\nXLM-Roberta & 0.93 & 0.96 & 0.96 & 0.92 & 0.90 \\\\\nGermanBERT & 0.90 & 0.94 & 0.91 & 0.91 & 0.88 \\\\\nDistilbert & 0.92 & 0.94 & 0.96 & 0.91 & 0.88 \\\\\nGBERT & 0.90 & 0.94 & 0.92 & 0.90 & 0.88 \\\\\nhmBERT & 0.89 & 0.93 & 0.92 & 0.90 & 0.84 \\\\\nEurop-Electra & 0.88 & 0.91 & 0.90 & 0.90 & 0.84 \\\\\nhmBERT-mini & 0.84 & 0.89 & 0.86 & 0.86 & 0.80 \\\\\nhmBERT-tiny & 0.77 & 0.84 & 0.80 & 0.79 & 0.72 \\\\\n\\multicolumn{6}{c}{GermEval} \\\\\nGermanBERT & 0.88 & 0.89 & 0.93 & 0.90 & 0.79 \\\\\nGBERT & 0.88 & 0.89 & 0.94 & 0.89 & 0.78 \\\\\nXLM-Roberta & 0.86 & 0.87 & 0.91 & 0.88 & 0.76 \\\\\nEurop-Electra & 0.84 & 0.84 & 0.90 & 0.87 & 0.73 \\\\\nhmBERT & 0.82 & 0.83 & 0.88 & 0.86 & 0.69 \\\\\nRoberta & 0.81 & 0.83 & 0.87 & 0.83 & 0.71 \\\\\nDistilbert & 0.76 & 0.77 & 0.80 & 0.80 & 0.66 \\\\\nhmBERT-mini & 0.72 & 0.75 & 0.78 & 0.76 & 0.59 \\\\\nhmBERT-tiny & 0.63 & 0.66 & 0.66 & 0.69 & 0.50 \\\\\n\\bottomrule\n\\end{tabular}\n'

In [7]:
atab = []
for dataset, res in load_results('experiments/results-single.pkl').groupby(['train', 'test','model']):
    atab.append(res.sort_values('f1_test', ascending=False).iloc[[0]])
atab = pd.concat(atab).sort_values(['test','f1_early'], ascending=[True, False]).reset_index(drop=True)
atab = atab.loc[atab.test==atab.train].reset_index(drop=True)

test_val_diff = (atab['f1_test'] - atab['f1_early']).abs()
print('Average distance between early stopping f_1-score and test f_1-score: {}+-{}'.\
      format(test_val_diff.mean().round(2), test_val_diff.std().round(2)))

res_single = atab


res_single[['test','train', 'model', 'epoch', 'f1_test', 'f1_early', 'PER_f1_test','LOC_f1_test', 'ORG_f1_test', 'learning_rate', 'batch_size']]

Number of results so far:  6597
Average distance between early stopping f_1-score and test f_1-score: 0.02+-0.02

,test,train,model,epoch,f1_test,f1_early,PER_f1_test,LOC_f1_test,ORG_f1_test,learning_rate,batch_size
0,GermEval,GermEval,bert-base-german-cased,4,0.88,0.89,0.93,0.90,0.79,2e-05,32
1,GermEval,GermEval,gbert-base,2,0.88,0.89,0.94,0.89,0.78,4e-05,64
2,GermEval,GermEval,xlm-roberta-base,3,0.86,0.87,0.91,0.88,0.76,2e-05,32
3,GermEval,GermEval,electra-base-german-europeana-cased-discriminator,3,0.84,0.84,0.90,0.87,0.73,4e-05,32
4,GermEval,GermEval,bert-base-historic-multilingual-cased,4,0.82,0.83,0.88,0.86,0.69,4e-05,64
5,GermEval,GermEval,roberta-base,4,0.81,0.83,0.87,0.83,0.71,2e-05,32
6,GermEval,GermEval,distilbert-base-uncased,6,0.76,0.77,0.80,0.80,0.66,0.0001,96
7,GermEval,GermEval,bert-mini-historic-multilingual-cased,10,0.72,0.75,0.78,0.76,0.59,4e-05,32
8,GermEval,GermEval,bert-tiny-historic-multilingual-cased,8,0.63,0.66,0.66,0.69,0.50,0.0001,32
9,conll2003,conll2003,roberta-base,4,0.94,0.97,0.96,0.93,0.92,2e-05,96
10,conll2003,conll2003,xlm-roberta-base,4,0.93,0.96,0.96,0.92,0.90,2e-05,32
11,conll2003,conll2003,bert-base-german-cased,6,0.90,0.94,0.91,0.91,0.88,2e-05,32
12,conll2003,conll2003,distilbert-base-uncased,3,0.92,0.94,0.96,0.91,0.88,0.0001,64
13,conll2003,conll2003,gbert-base,4,0.90,0.94,0.92,0.90,0.88,2e-05,32
14,conll2003,conll2003,bert-base-historic-multilingual-cased,4,0.89,0.93,0.92,0.90,0.84,4e-05,32
15,conll2003,conll2003,electra-base-german-europeana-cased-discriminator,6,0.88,0.91,0.90,0.90,0.84,4e-05,96
16,conll2003,conll2003,bert-mini-historic-multilingual-cased,6,0.84,0.89,0.86,0.86,0.80,0.0001,32
17,conll2003,conll2003,bert-tiny-historic-multilingual-cased,13,0.77,0.84,0.80,0.79,0.72,0.0001,64
18,europeana-lft,europeana-lft,roberta-base,10,0.76,0.77,0.76,0.78,0.69,4e-05,32
19,europeana-lft,europeana-lft,xlm-roberta-base,7,0.78,0.77,0.80,0.80,0.68,4e-05,32
20,europeana-lft,europeana-lft,bert-base-historic-multilingual-cased,9,0.76,0.76,0.82,0.78,0.60,4e-05,32
21,europeana-lft,europeana-lft,electra-base-german-europeana-cased-discriminator,5,0.79,0.76,0.81,0.80,0.69,0.0001,32
22,europeana-lft,europeana-lft,gbert-base,4,0.74,0.75,0.77,0.75,0.63,0.0001,64
23,europeana-lft,europeana-lft,bert-base-german-cased,3,0.73,0.73,0.77,0.75,0.59,0.0001,32
24,europeana-lft,europeana-lft,distilbert-base-uncased,5,0.65,0.67,0.59,0.73,0.53,0.0001,32
25,europeana-lft,europeana-lft,bert-mini-historic-multilingual-cased,11,0.63,0.66,0.64,0.68,0.48,0.0001,32
26,europeana-lft,europeana-lft,bert-tiny-historic-multilingual-cased,14,0.50,0.54,0.47,0.57,0.35,0.0001,32
27,europeana-onb,europeana-onb,electra-base-german-europeana-cased-discriminator,18,0.84,0.82,0.79,0.90,0.30,2e-05,32
28,europeana-onb,europeana-onb,xlm-roberta-base,5,0.84,0.81,0.78,0.90,0.21,0.0001,32
29,europeana-onb,europeana-onb,bert-base-historic-multilingual-cased,8,0.84,0.80,0.75,0.91,0.44,4e-05,32
30,europeana-onb,europeana-onb,gbert-base,4,0.83,0.80,0.73,0.92,0.29,0.0001,32
31,europeana-onb,europeana-onb,bert-base-german-cased,7,0.82,0.79,0.76,0.87,0.36,4e-05,32
32,europeana-onb,europeana-onb,roberta-base,7,0.81,0.77,0.77,0.84,0.29,4e-05,32
33,europeana-onb,europeana-onb,bert-mini-historic-multilingual-cased,7,0.70,0.69,0.58,0.80,0.43,0.0001,32
34,europeana-onb,europeana-onb,distilbert-base-uncased,8,0.70,0.69,0.57,0.80,0.07,0.0001,32
35,europeana-onb,europeana-onb,bert-tiny-historic-multilingual-cased,22,0.50,0.46,0.31,0.66,0.00,0.0001,32
36,hipe2020,hipe2020,electra-base-german-europeana-cased-discriminator,4,0.76,0.77,0.77,0.82,0.52,0.0001,64
37,hipe2020,hipe2020,bert-base-german-cased,6,0.73,0.76,0.72,0.80,0.48,4e-05,32
38,hipe2020,hipe2020,bert-base-historic-multilingual-cased,10,0.73,0.76,0.72,0.79,0.55,2e-05,32
39,hipe2020,hipe2020,gbert-base,6,0.74,0.75,0.72,0.81,0.48,0.0001,32
40,hipe2020,hipe2020,xlm-roberta-base,9,0.73,0.73,0.68,0.81,0.50,2e-05,64
41,hipe2020,hipe2020,roberta-base,14,0.67,0.69,0.65,0.74,0.43,2e-05,64
42,hipe2020,hipe2020,distilbert-base-uncased,10,0.60,0.59,0.47,0.71,0.37,0.0001,64
43,hipe2020,hipe2020,bert-mini-historic-multilingual-cased,8,0.57,0.57,0.48,0.67,0.36,0.0001,32
44,hipe2020,hipe2020,bert-tiny-historic-multilingual-cased,14,0.40,0.40,0.24,0.53,0.23,0.0001,32
45,hisgerman,hisgerman,electra-base-german-europeana-cased-discriminator,10,0.80,0.76,0.80,0.84,0.00,2e-05,64
46,hisgerman,hisgerman,gbert-base,7,0.78,0.75,0.78,0.81,0.00,2e-05,32
47,hisgerman,hisgerman,bert-base-historic-multilingual-cased,9,0.80,0.74,0.81,0.84,0.00,4e-05,96
48,hisgerman,hisgerman,roberta-base,8,0.71,0.72,0.67,0.78,0.00,4e-05,64
49,hisgerman,hisgerman,xlm-roberta-base,9,0.74,0.71,0.72,0.80,0.00,2e-05,32
50,hisgerman,hisgerman,bert-base-german-cased,7,0.77,0.70,0.76,0.81,0.00,4e-05,96
51,hisgerman,hisgerman,bert-mini-historic-multilingual-cased,12,0.60,0.62,0.51,0.71,0.00,0.0001,96
52,hisgerman,hisgerman,distilbert-base-uncased,8,0.61,0.62,0.55,0.69,0.00,4e-05,32
53,hisgerman,hisgerman,bert-tiny-historic-multilingual-cased,12,0.30,0.30,0.18,0.42,0.00,0.0001,32
54,neiss-arendt,neiss-arendt,roberta-base,11,0.86,0.90,0.92,0.85,0.64,4e-05,64
55,neiss-arendt,neiss-arendt,bert-base-german-cased,5,0.88,0.89,0.94,0.83,0.74,2e-05,32
56,neiss-arendt,neiss-arendt,bert-base-historic-multilingual-cased,5,0.87,0.89,0.92,0.84,0.72,4e-05,32
57,neiss-arendt,neiss-arendt,gbert-base,5,0.87,0.89,0.95,0.78,0.73,4e-05,32
58,neiss-arendt,neiss-arendt,xlm-roberta-base,5,0.86,0.89,0.92,0.84,0.73,2e-05,32
59,neiss-arendt,neiss-arendt,bert-mini-historic-multilingual-cased,5,0.85,0.87,0.91,0.81,0.69,0.0001,32
60,neiss-arendt,neiss-arendt,distilbert-base-uncased,6,0.85,0.87,0.93,0.78,0.63,2e-05,32
61,neiss-arendt,neiss-arendt,electra-base-german-europeana-cased-discriminator,7,0.86,0.86,0.93,0.80,0.75,2e-05,32
62,neiss-arendt,neiss-arendt,bert-tiny-historic-multilingual-cased,5,0.79,0.79,0.83,0.75,0.73,0.0001,64
63,neiss-sturm,neiss-sturm,bert-base-german-cased,5,0.91,0.95,0.93,0.86,NaN,0.0001,64
64,neiss-sturm,neiss-sturm,xlm-roberta-base,9,0.90,0.95,0.91,0.88,NaN,0.0001,96
65,neiss-sturm,neiss-sturm,gbert-base,4,0.89,0.94,0.91,0.84,NaN,0.0001,32
66,neiss-sturm,neiss-sturm,electra-base-german-europeana-cased-discriminator,4,0.89,0.93,0.91,0.83,NaN,2e-05,32
67,neiss-sturm,neiss-sturm,roberta-base,14,0.88,0.92,0.93,0.79,NaN,0.0001,64
68,neiss-sturm,neiss-sturm,bert-base-historic-multilingual-cased,4,0.91,0.91,0.94,0.83,NaN,0.0001,96
69,neiss-sturm,neiss-sturm,distilbert-base-uncased,6,0.85,0.90,0.88,0.80,NaN,0.0001,96
70,neiss-sturm,neiss-sturm,bert-mini-historic-multilingual-cased,16,0.82,0.85,0.86,0.75,NaN,4e-05,64
71,neiss-sturm,neiss-sturm,bert-tiny-historic-multilingual-cased,11,0.71,0.84,0.73,0.67,NaN,0.0001,32
72,zefys2025,zefys2025,electra-base-german-europeana-cased-discriminator,5,0.83,0.85,0.85,0.88,0.69,2e-05,32
73,zefys2025,zefys2025,bert-base-german-cased,3,0.82,0.83,0.83,0.88,0.68,4e-05,32
74,zefys2025,zefys2025,bert-base-historic-multilingual-cased,6,0.83,0.83,0.85,0.88,0.71,4e-05,64
75,zefys2025,zefys2025,gbert-base,3,0.82,0.83,0.83,0.88,0.67,4e-05,32
76,zefys2025,zefys2025,xlm-roberta-base,7,0.80,0.81,0.80,0.87,0.67,2e-05,32
77,zefys2025,zefys2025,roberta-base,7,0.78,0.79,0.79,0.85,0.65,4e-05,96
78,zefys2025,zefys2025,distilbert-base-uncased,10,0.75,0.74,0.74,0.82,0.64,4e-05,64
79,zefys2025,zefys2025,bert-mini-historic-multilingual-cased,10,0.72,0.71,0.70,0.80,0.57,0.0001,64
80,zefys2025,zefys2025,bert-tiny-historic-multilingual-cased,9,0.60,0.62,0.58,0.70,0.42,0.0001,32

In [8]:
atab = []
for dataset, res in load_results('experiments/results-single.pkl').groupby(['train', 'test','model']):
    atab.append(res.sort_values('f1_test', ascending=False).iloc[[0]])
atab = pd.concat(atab).sort_values(['f1_test','f1_early'], ascending=[False, False]).reset_index(drop=True)
atab = atab.loc[atab.train=="zefys2025"]

test_val_diff = (atab['f1_test'] - atab['f1_early']).abs()
print('Average distance between early stopping f_1-score and test f_1-score: {}+-{}'.\
      format(test_val_diff.mean().round(2), test_val_diff.std().round(2)))

atab_zefys = atab.loc[(atab.test=="zefys2025") & (atab.train=="zefys2025")]
test_val_diff = (atab_zefys['f1_test'] - atab_zefys['f1_early']).abs()
print('ZEFYS2025 - Average distance between early stopping f_1-score and test f_1-score: {}+-{}'.\
      format(test_val_diff.mean().round(2), test_val_diff.std().round(2)))

btab = []
for data, res in atab.groupby('test', sort=False):
    btab.append(res.iloc[[0]])
btab = pd.concat(btab)    

#res_single[['test','train', 'model', 'epoch', 'f1_test', 'f1_early', 'PER_f1_test','LOC_f1_test', 'ORG_f1_test', 'learning_rate', 'batch_size']]
btab[['test','train', 'model', 'epoch', 'f1_test', 'f1_early', 'PER_f1_test','LOC_f1_test', 'ORG_f1_test', 'learning_rate', 'batch_size']]

Number of results so far:  6597
Average distance between early stopping f_1-score and test f_1-score: 0.17+-0.09
ZEFYS2025 - Average distance between early stopping f_1-score and test f_1-score: 0.01+-0.01

,test,train,model,epoch,f1_test,f1_early,PER_f1_test,LOC_f1_test,ORG_f1_test,learning_rate,batch_size
30,zefys2025,zefys2025,electra-base-german-europeana-cased-discriminator,5,0.83,0.85,0.85,0.88,0.69,2e-05,32
47,GermEval,zefys2025,bert-base-german-cased,4,0.78,0.81,0.89,0.82,0.59,2e-05,64
78,europeana-onb,zefys2025,electra-base-german-europeana-cased-discriminator,5,0.72,0.85,0.61,0.82,0.09,2e-05,32
79,hisgerman,zefys2025,electra-base-german-europeana-cased-discriminator,5,0.72,0.84,0.69,0.77,0.11,4e-05,96
107,neiss-arendt,zefys2025,bert-base-historic-multilingual-cased,6,0.68,0.83,0.79,0.79,0.07,4e-05,64
121,neiss-sturm,zefys2025,xlm-roberta-base,6,0.67,0.80,0.71,0.59,0.00,2e-05,64
171,hipe2020,zefys2025,electra-base-german-europeana-cased-discriminator,6,0.63,0.84,0.45,0.78,0.42,2e-05,64
192,conll2003,zefys2025,xlm-roberta-base,7,0.62,0.81,0.84,0.66,0.41,2e-05,32
214,europeana-lft,zefys2025,bert-base-historic-multilingual-cased,4,0.61,0.81,0.62,0.67,0.46,4e-05,96

# ZEFYS2025 Pre-Training Configs

In [9]:
atab = []
for dataset, res in load_results('experiments/zefys-pretrained/pretrained-on-zefys-configs.pkl').groupby(['test', 'model']):
    atab.append(res.sort_values('f1_test', ascending=False).iloc[[0]])
atab = pd.concat(atab).sort_values(['test','f1_early'], ascending=[True, False]).reset_index(drop=True)

zefys_pretrained_configs_table, df_zefys_pretrained_configs = make_nice_table(atab, ['zefys2025'], ['f1_test', 'f1_early',], [], additional_columns=['dataset','model','learning_rate'])
zefys_pretrained_configs_table

Number of results so far:  9

# All-Historical Pre-Training Configs

In [10]:
atab = []
for dataset, res in load_results('experiments/all-historic-pretrained/pretrained-on-all-historic-configs.pkl').groupby(['test', 'model']):
    atab.append(res.sort_values('f1_test', ascending=False).iloc[[0]])
atab = pd.concat(atab).sort_values(['test','f1_early'], ascending=[True, False]).reset_index(drop=True)

all_historic_pretrained_configs_table, df_all_historic_pretrained_configs = make_nice_table(atab, ['all-historic'], ['f1_test', 'f1_early',], [], 
                                                dataset_column='train', additional_columns =['dataset', 'test', 'model', 'learning_rate', 'batch_size'])
all_historic_pretrained_configs_table

Number of results so far:  63

## pretrained-on-zefys

In [11]:
atab = []
for dataset, res in load_results('experiments/results-pretrained-zefys.pkl').groupby(['train', 'test','pretrain', 'model']):
    atab.append(res.sort_values('f1_test', ascending=False).iloc[[0]])
atab = pd.concat(atab).sort_values(['test','f1_early'], ascending=[True, False]).reset_index(drop=True)
res_pretrained_zefys2=atab
atab[['test', 'pretrain', 'model', 'epoch', 'f1_test', 'f1_early', 'PER_f1_test','LOC_f1_test', 'ORG_f1_test', 'learning_rate', 'batch_size']]

Number of results so far:  486

,test,pretrain,model,epoch,f1_test,f1_early,PER_f1_test,LOC_f1_test,ORG_f1_test,learning_rate,batch_size
0,europeana-lft,zefys2025,electra-base-german-europeana-cased-discriminator,5,0.80,0.79,0.83,0.81,0.67,4e-05,32
1,europeana-lft,zefys2025,xlm-roberta-base,4,0.78,0.78,0.81,0.79,0.70,4e-05,64
2,europeana-lft,zefys2025,bert-base-historic-multilingual-cased,3,0.76,0.77,0.77,0.77,0.68,0.0001,32
3,europeana-lft,zefys2025,bert-base-german-cased,8,0.73,0.76,0.76,0.76,0.59,4e-05,32
4,europeana-lft,zefys2025,gbert-base,4,0.73,0.75,0.76,0.75,0.60,0.0001,64
5,europeana-lft,zefys2025,roberta-base,10,0.75,0.75,0.75,0.78,0.65,4e-05,96
6,europeana-lft,zefys2025,distilbert-base-uncased,5,0.67,0.69,0.63,0.73,0.59,0.0001,64
7,europeana-lft,zefys2025,bert-mini-historic-multilingual-cased,7,0.67,0.67,0.66,0.72,0.53,0.0001,96
8,europeana-lft,zefys2025,bert-tiny-historic-multilingual-cased,15,0.55,0.58,0.53,0.63,0.39,0.0001,64
9,europeana-onb,zefys2025,xlm-roberta-base,9,0.88,0.85,0.85,0.92,0.13,0.0001,32
10,europeana-onb,zefys2025,electra-base-german-europeana-cased-discriminator,6,0.86,0.84,0.77,0.93,0.37,4e-05,32
11,europeana-onb,zefys2025,bert-base-german-cased,5,0.83,0.82,0.75,0.89,0.44,4e-05,32
12,europeana-onb,zefys2025,bert-base-historic-multilingual-cased,2,0.86,0.82,0.78,0.92,0.50,0.0001,32
13,europeana-onb,zefys2025,gbert-base,4,0.84,0.81,0.75,0.92,0.40,4e-05,32
14,europeana-onb,zefys2025,roberta-base,8,0.84,0.81,0.80,0.87,0.30,4e-05,64
15,europeana-onb,zefys2025,bert-mini-historic-multilingual-cased,10,0.76,0.71,0.66,0.85,0.33,0.0001,96
16,europeana-onb,zefys2025,distilbert-base-uncased,5,0.74,0.70,0.63,0.83,0.15,4e-05,32
17,europeana-onb,zefys2025,bert-tiny-historic-multilingual-cased,14,0.63,0.63,0.45,0.77,0.31,0.0001,32
18,hipe2020,zefys2025,electra-base-german-europeana-cased-discriminator,9,0.78,0.79,0.75,0.84,0.57,2e-05,32
19,hipe2020,zefys2025,gbert-base,6,0.74,0.78,0.71,0.81,0.50,4e-05,32
20,hipe2020,zefys2025,bert-base-german-cased,6,0.76,0.77,0.75,0.81,0.60,4e-05,32
21,hipe2020,zefys2025,bert-base-historic-multilingual-cased,6,0.75,0.77,0.72,0.82,0.54,2e-05,32
22,hipe2020,zefys2025,xlm-roberta-base,8,0.74,0.73,0.71,0.82,0.50,4e-05,32
23,hipe2020,zefys2025,roberta-base,6,0.70,0.71,0.68,0.77,0.50,2e-05,64
24,hipe2020,zefys2025,bert-mini-historic-multilingual-cased,5,0.58,0.61,0.50,0.69,0.33,0.0001,32
25,hipe2020,zefys2025,distilbert-base-uncased,6,0.62,0.60,0.52,0.74,0.33,2e-05,32
26,hipe2020,zefys2025,bert-tiny-historic-multilingual-cased,7,0.48,0.47,0.35,0.61,0.23,4e-05,32
27,hisgerman,zefys2025,electra-base-german-europeana-cased-discriminator,3,0.84,0.80,0.86,0.86,0.15,0.0001,64
28,hisgerman,zefys2025,gbert-base,2,0.80,0.76,0.81,0.83,0.13,4e-05,32
29,hisgerman,zefys2025,bert-base-historic-multilingual-cased,3,0.82,0.75,0.83,0.85,0.00,4e-05,32
30,hisgerman,zefys2025,bert-base-german-cased,3,0.79,0.74,0.80,0.81,0.25,4e-05,32
31,hisgerman,zefys2025,xlm-roberta-base,5,0.79,0.73,0.79,0.84,0.00,2e-05,64
32,hisgerman,zefys2025,roberta-base,5,0.76,0.72,0.79,0.78,0.08,2e-05,64
33,hisgerman,zefys2025,distilbert-base-uncased,7,0.67,0.67,0.62,0.74,0.11,2e-05,32
34,hisgerman,zefys2025,bert-mini-historic-multilingual-cased,6,0.68,0.66,0.63,0.76,0.00,0.0001,96
35,hisgerman,zefys2025,bert-tiny-historic-multilingual-cased,5,0.51,0.45,0.43,0.61,0.00,0.0001,64
36,neiss-arendt,zefys2025,xlm-roberta-base,4,0.86,0.91,0.92,0.82,0.74,2e-05,32
37,neiss-arendt,zefys2025,bert-base-german-cased,2,0.88,0.90,0.94,0.83,0.74,4e-05,32
38,neiss-arendt,zefys2025,bert-base-historic-multilingual-cased,5,0.88,0.89,0.94,0.85,0.71,4e-05,32
39,neiss-arendt,zefys2025,distilbert-base-uncased,2,0.87,0.89,0.92,0.80,0.72,4e-05,96
40,neiss-arendt,zefys2025,bert-mini-historic-multilingual-cased,5,0.86,0.88,0.91,0.84,0.70,4e-05,32
41,neiss-arendt,zefys2025,electra-base-german-europeana-cased-discriminator,5,0.86,0.88,0.93,0.82,0.74,0.0001,32
42,neiss-arendt,zefys2025,gbert-base,3,0.87,0.88,0.94,0.82,0.69,2e-05,32
43,neiss-arendt,zefys2025,roberta-base,3,0.87,0.88,0.92,0.83,0.72,2e-05,64
44,neiss-arendt,zefys2025,bert-tiny-historic-multilingual-cased,6,0.83,0.84,0.89,0.82,0.64,0.0001,32
45,neiss-sturm,zefys2025,bert-base-german-cased,4,0.91,0.94,0.93,0.87,NaN,2e-05,64
46,neiss-sturm,zefys2025,gbert-base,5,0.91,0.94,0.95,0.84,NaN,4e-05,96
47,neiss-sturm,zefys2025,xlm-roberta-base,9,0.93,0.94,0.95,0.88,NaN,2e-05,96
48,neiss-sturm,zefys2025,electra-base-german-europeana-cased-discriminator,4,0.92,0.93,0.92,0.90,NaN,2e-05,32
49,neiss-sturm,zefys2025,roberta-base,6,0.91,0.93,0.95,0.86,NaN,4e-05,96
50,neiss-sturm,zefys2025,bert-base-historic-multilingual-cased,5,0.91,0.92,0.93,0.86,NaN,4e-05,64
51,neiss-sturm,zefys2025,distilbert-base-uncased,6,0.88,0.91,0.88,0.88,NaN,0.0001,96
52,neiss-sturm,zefys2025,bert-mini-historic-multilingual-cased,4,0.86,0.87,0.90,0.79,NaN,0.0001,32
53,neiss-sturm,zefys2025,bert-tiny-historic-multilingual-cased,8,0.75,0.84,0.77,0.72,NaN,0.0001,32

## pretrained-on-all-historical

In [12]:
atab = []
for dataset, res in load_results('experiments/results-pretrained-all-historic.pkl').groupby(['train', 'test','pretrain', 'model']):
    atab.append(res.sort_values('f1_test', ascending=False).iloc[[0]])
atab = pd.concat(atab).sort_values(['test','f1_early'], ascending=[True, False]).reset_index(drop=True)
res_pretrained_all2=atab
atab[['test', 'pretrain', 'model', 'epoch', 'f1_test', 'f1_early', 'PER_f1_test','LOC_f1_test', 'ORG_f1_test', 'learning_rate', 'batch_size']]

Number of results so far:  547

,test,pretrain,model,epoch,f1_test,f1_early,PER_f1_test,LOC_f1_test,ORG_f1_test,learning_rate,batch_size
0,europeana-lft,all-historic,xlm-roberta-base,4,0.78,0.80,0.81,0.80,0.66,2e-05,96
1,europeana-lft,all-historic,bert-base-historic-multilingual-cased,4,0.77,0.78,0.79,0.79,0.68,2e-05,96
2,europeana-lft,all-historic,electra-base-german-europeana-cased-discriminator,4,0.79,0.78,0.82,0.82,0.66,2e-05,32
3,europeana-lft,all-historic,gbert-base,1,0.73,0.76,0.74,0.75,0.62,4e-05,64
4,europeana-lft,all-historic,roberta-base,5,0.76,0.76,0.78,0.79,0.66,4e-05,64
5,europeana-lft,all-historic,bert-base-german-cased,1,0.74,0.74,0.77,0.75,0.62,0.0001,64
6,europeana-lft,all-historic,distilbert-base-uncased,3,0.66,0.70,0.62,0.73,0.56,4e-05,32
7,europeana-lft,all-historic,bert-mini-historic-multilingual-cased,4,0.65,0.67,0.67,0.70,0.51,0.0001,96
8,europeana-lft,all-historic,bert-tiny-historic-multilingual-cased,9,0.58,0.60,0.57,0.64,0.44,0.0001,32
9,europeana-onb,all-historic,xlm-roberta-base,3,0.86,0.86,0.79,0.92,0.65,0.0001,64
10,europeana-onb,all-historic,electra-base-german-europeana-cased-discriminator,3,0.88,0.85,0.82,0.94,0.44,4e-05,32
11,europeana-onb,all-historic,bert-base-historic-multilingual-cased,2,0.86,0.84,0.81,0.90,0.44,0.0001,64
12,europeana-onb,all-historic,gbert-base,2,0.83,0.83,0.77,0.88,0.38,4e-05,32
13,europeana-onb,all-historic,roberta-base,4,0.87,0.81,0.81,0.92,0.20,4e-05,96
14,europeana-onb,all-historic,bert-base-german-cased,7,0.84,0.80,0.73,0.92,0.53,2e-05,64
15,europeana-onb,all-historic,distilbert-base-uncased,3,0.75,0.73,0.61,0.86,0.15,0.0001,32
16,europeana-onb,all-historic,bert-mini-historic-multilingual-cased,1,0.78,0.72,0.68,0.86,0.28,0.0001,32
17,europeana-onb,all-historic,bert-tiny-historic-multilingual-cased,2,0.65,0.63,0.48,0.78,0.38,0.0001,32
18,hipe2020,all-historic,bert-base-historic-multilingual-cased,6,0.75,0.78,0.70,0.82,0.57,0.0001,96
19,hipe2020,all-historic,electra-base-german-europeana-cased-discriminator,3,0.75,0.78,0.72,0.82,0.51,0.0001,32
20,hipe2020,all-historic,bert-base-german-cased,6,0.74,0.76,0.72,0.81,0.46,0.0001,32
21,hipe2020,all-historic,gbert-base,5,0.74,0.76,0.67,0.83,0.48,4e-05,96
22,hipe2020,all-historic,xlm-roberta-base,5,0.74,0.73,0.67,0.84,0.53,4e-05,32
23,hipe2020,all-historic,roberta-base,3,0.70,0.72,0.65,0.78,0.46,4e-05,32
24,hipe2020,all-historic,distilbert-base-uncased,4,0.62,0.63,0.50,0.75,0.35,4e-05,64
25,hipe2020,all-historic,bert-mini-historic-multilingual-cased,4,0.62,0.62,0.50,0.74,0.38,0.0001,64
26,hipe2020,all-historic,bert-tiny-historic-multilingual-cased,4,0.51,0.49,0.36,0.64,0.31,0.0001,32
27,hisgerman,all-historic,bert-base-historic-multilingual-cased,5,0.84,0.78,0.88,0.84,0.21,4e-05,96
28,hisgerman,all-historic,electra-base-german-europeana-cased-discriminator,5,0.81,0.78,0.80,0.85,0.19,4e-05,64
29,hisgerman,all-historic,bert-base-german-cased,4,0.82,0.77,0.81,0.87,0.16,4e-05,32
30,hisgerman,all-historic,gbert-base,3,0.81,0.76,0.84,0.84,0.00,4e-05,64
31,hisgerman,all-historic,xlm-roberta-base,4,0.82,0.76,0.82,0.85,0.17,2e-05,32
32,hisgerman,all-historic,roberta-base,2,0.79,0.71,0.81,0.82,0.00,4e-05,64
33,hisgerman,all-historic,bert-mini-historic-multilingual-cased,3,0.72,0.68,0.73,0.76,0.00,0.0001,32
34,hisgerman,all-historic,distilbert-base-uncased,4,0.74,0.66,0.72,0.78,0.10,0.0001,96
35,hisgerman,all-historic,bert-tiny-historic-multilingual-cased,7,0.58,0.55,0.51,0.67,0.00,0.0001,32
36,neiss-arendt,all-historic,bert-base-german-cased,2,0.88,0.90,0.94,0.82,0.73,4e-05,64
37,neiss-arendt,all-historic,bert-base-historic-multilingual-cased,2,0.87,0.90,0.95,0.83,0.69,2e-05,32
38,neiss-arendt,all-historic,distilbert-base-uncased,3,0.87,0.90,0.93,0.82,0.65,4e-05,96
39,neiss-arendt,all-historic,xlm-roberta-base,2,0.87,0.89,0.93,0.85,0.69,2e-05,32
40,neiss-arendt,all-historic,gbert-base,2,0.88,0.88,0.95,0.81,0.71,4e-05,96
41,neiss-arendt,all-historic,roberta-base,3,0.87,0.88,0.93,0.83,0.66,4e-05,96
42,neiss-arendt,all-historic,bert-mini-historic-multilingual-cased,2,0.84,0.87,0.91,0.82,0.60,4e-05,32
43,neiss-arendt,all-historic,electra-base-german-europeana-cased-discriminator,3,0.86,0.87,0.93,0.80,0.71,0.0001,96
44,neiss-arendt,all-historic,bert-tiny-historic-multilingual-cased,4,0.83,0.85,0.90,0.79,0.65,0.0001,32
45,neiss-sturm,all-historic,bert-base-german-cased,4,0.90,0.94,0.94,0.83,NaN,4e-05,64
46,neiss-sturm,all-historic,electra-base-german-europeana-cased-discriminator,1,0.92,0.94,0.93,0.89,NaN,4e-05,96
47,neiss-sturm,all-historic,gbert-base,4,0.91,0.94,0.93,0.87,NaN,2e-05,64
48,neiss-sturm,all-historic,xlm-roberta-base,4,0.93,0.94,0.96,0.87,NaN,2e-05,32
49,neiss-sturm,all-historic,roberta-base,5,0.91,0.93,0.92,0.88,NaN,2e-05,32
50,neiss-sturm,all-historic,bert-mini-historic-multilingual-cased,5,0.86,0.90,0.89,0.78,NaN,0.0001,32
51,neiss-sturm,all-historic,bert-base-historic-multilingual-cased,1,0.91,0.89,0.92,0.89,NaN,4e-05,32
52,neiss-sturm,all-historic,distilbert-base-uncased,4,0.90,0.89,0.92,0.86,NaN,2e-05,32
53,neiss-sturm,all-historic,bert-tiny-historic-multilingual-cased,6,0.78,0.88,0.79,0.74,NaN,0.0001,32
54,zefys2025,all-historic,electra-base-german-europeana-cased-discriminator,3,0.84,0.85,0.84,0.89,0.70,2e-05,32
55,zefys2025,all-historic,bert-base-german-cased,4,0.83,0.83,0.84,0.89,0.70,4e-05,64
56,zefys2025,all-historic,bert-base-historic-multilingual-cased,5,0.83,0.83,0.84,0.89,0.70,2e-05,32
57,zefys2025,all-historic,gbert-base,3,0.81,0.82,0.83,0.87,0.65,2e-05,32
58,zefys2025,all-historic,xlm-roberta-base,2,0.81,0.82,0.82,0.87,0.67,2e-05,32
59,zefys2025,all-historic,roberta-base,7,0.80,0.80,0.80,0.87,0.69,2e-05,32
60,zefys2025,all-historic,distilbert-base-uncased,6,0.75,0.75,0.75,0.81,0.64,4e-05,32
61,zefys2025,all-historic,bert-mini-historic-multilingual-cased,5,0.72,0.71,0.73,0.79,0.55,2e-05,32
62,zefys2025,all-historic,bert-tiny-historic-multilingual-cased,5,0.64,0.62,0.61,0.74,0.46,0.0001,32

In [13]:
merged_results2 = merge_historical_results(res_single, res_pretrained_zefys2, res_pretrained_all2)
merged_results2.columns

Index(['precision', 'recall', 'f1', 'accuracy', 'f1_early', 'epoch', 'model',
       'train', 'train_params', 'f1_test', 'precision_test', 'recall_test',
       'PER_f1_best', 'PER_precision_test', 'PER_recall_test', 'LOC_f1_best',
       'LOC_precision_test', 'LOC_recall_test', 'ORG_f1_best',
       'ORG_precision_test', 'ORG_recall_test', 'test', 'exp_ID', 'batch_size',
       'learning_rate', 'pretrain', 'pretrained_model'],
      dtype='object')

Index(['precision', 'recall', 'f1', 'accuracy', 'f1_early', 'epoch', 'model',
       'train', 'train_params', 'f1_test', 'precision_test', 'recall_test',
       'PER_f1_test', 'PER_precision_test', 'PER_recall_test', 'LOC_f1_test',
       'LOC_precision_test', 'LOC_recall_test', 'ORG_f1_test',
       'ORG_precision_test', 'ORG_recall_test', 'test', 'exp_ID', 'batch_size',
       'learning_rate', 'precision_PZ', 'recall_PZ', 'f1_PZ', 'accuracy_PZ',
       'f1_early_PZ', 'epoch_PZ', 'train_params_PZ', 'f1_test_PZ',
       'precision_test_PZ', 'recall_test_PZ', 'PER_f1_test_PZ',
       'PER_precision_test_PZ', 'PER_recall_test_PZ', 'LOC_f1_test_PZ',
       'LOC_precision_test_PZ', 'LOC_recall_test_PZ', 'ORG_f1_test_PZ',
       'ORG_precision_test_PZ', 'ORG_recall_test_PZ', 'pretrained_model',
       'exp_ID_PZ', 'batch_size_PZ', 'learning_rate_PZ', 'precision_PA',
       'recall_PA', 'f1_PA', 'accuracy_PA', 'f1_early_PA', 'epoch_PA',
       'train_params_PA', 'f1_test_PA', 'precision_test_PA', 'recall_test_PA',
       'PER_f1_test_PA', 'PER_precision_test_PA', 'PER_recall_test_PA',
       'LOC_f1_test_PA', 'LOC_precision_test_PA', 'LOC_recall_test_PA',
       'ORG_f1_test_PA', 'ORG_precision_test_PA', 'ORG_recall_test_PA',
       'pretrained_model_PA', 'exp_ID_PA', 'batch_size_PA', 'learning_rate_PA',
       'PER_f1_best', 'LOC_f1_best', 'ORG_f1_best'],
      dtype='object')

#### Zefys2025 Results without Pretraining/with Pretraining on All-Historical

In [14]:
newdataset_table2, df_newdataset2 = make_nice_table(merged_results2,
                                                  ['zefys2025'], ['f1_test', 'f1_test_PA', 'PER_f1_best', 'LOC_f1_best', 'ORG_f1_best'], 
                                                  ['f1_test', 'f1_test_PA'])
newdataset_table2

In [15]:
write_to_latex_file(newdataset_table2,'tables/newdataset.tex', df_newdataset2.shape[1])

'\\begin{tabular}{lrrrrr}\n\\toprule\nmodel & $f1_{test}$ & $f1_{test}_{PA}$ & $PER_{f1}_{best}$ & $LOC_{f1}_{best}$ & $ORG_{f1}_{best}$ \\\\\n\\midrule\n\\multicolumn{6}{c}{Anon2025} \\\\\nEurop-Electra & 0.83 & \\bf 0.84 & 0.84 & 0.89 & 0.70 \\\\\nhmBERT & \\bf 0.83 & \\bf 0.83 & 0.85 & 0.88 & 0.71 \\\\\nGermanBERT & 0.82 & \\bf 0.83 & 0.84 & 0.89 & 0.70 \\\\\nGBERT & \\bf 0.82 & 0.81 & 0.83 & 0.88 & 0.67 \\\\\nXLM-Roberta & 0.80 & \\bf 0.81 & 0.82 & 0.87 & 0.67 \\\\\nRoberta & 0.78 & \\bf 0.80 & 0.80 & 0.87 & 0.69 \\\\\nDistilbert & \\bf 0.75 & \\bf 0.75 & 0.74 & 0.82 & 0.64 \\\\\nhmBERT-mini & \\bf 0.72 & \\bf 0.72 & 0.70 & 0.80 & 0.57 \\\\\nhmBERT-tiny & 0.60 & \\bf 0.64 & 0.61 & 0.74 & 0.46 \\\\\n\\bottomrule\n\\end{tabular}\n'

# Historical Datasets Results without Pretraining/with Pretraining on ZEFYS2025/with Pretraining on All-Historical

In [16]:
hist_table2, df_hist_table2 = make_nice_table(merged_results2,
                                            ['hisgerman', 'europeana-lft', 'europeana-onb', 'hipe2020', 'neiss-arendt', 'neiss-sturm'],
                                            ['f1_test', 'f1_test_PZ', 'f1_test_PA', 'PER_f1_best', 'LOC_f1_best', 'ORG_f1_best'], 
                                            ['f1_test', 'f1_test_PZ', 'f1_test_PA'])
hist_table2

In [17]:
write_to_latex_file(hist_table2,'tables/historical_comparison.tex', df_hist_table2.shape[1])

'\\begin{tabular}{lrrrrrr}\n\\toprule\nmodel & $f1_{test}$ & $f1_{test}_{PZ}$ & $f1_{test}_{PA}$ & $PER_{f1}_{best}$ & $LOC_{f1}_{best}$ & $ORG_{f1}_{best}$ \\\\\n\\midrule\n\\multicolumn{7}{c}{HisGermanNER} \\\\\nhmBERT & 0.80 & 0.82 & \\bf 0.84 & 0.88 & 0.84 & 0.21 \\\\\nEurop-Electra & 0.80 & \\bf 0.84 & 0.81 & 0.86 & 0.86 & 0.15 \\\\\nGBERT & 0.78 & 0.80 & \\bf 0.81 & 0.84 & 0.84 & 0.00 \\\\\nGermanBERT & 0.77 & 0.79 & \\bf 0.82 & 0.81 & 0.87 & 0.16 \\\\\nXLM-Roberta & 0.74 & 0.79 & \\bf 0.82 & 0.82 & 0.85 & 0.17 \\\\\nRoberta & 0.71 & 0.76 & \\bf 0.79 & 0.81 & 0.82 & 0.00 \\\\\nDistilbert & 0.61 & 0.67 & \\bf 0.74 & 0.72 & 0.78 & 0.10 \\\\\nhmBERT-mini & 0.60 & 0.68 & \\bf 0.72 & 0.73 & 0.76 & 0.00 \\\\\nhmBERT-tiny & 0.30 & 0.51 & \\bf 0.58 & 0.51 & 0.67 & 0.00 \\\\\n\\multicolumn{7}{c}{Europeana-LFT} \\\\\nEurop-Electra & 0.79 & \\bf 0.80 & 0.79 & 0.83 & 0.81 & 0.67 \\\\\nXLM-Roberta & \\bf 0.78 & \\bf 0.78 & \\bf 0.78 & 0.80 & 0.80 & 0.68 \\\\\nhmBERT & 0.76 & 0.76 & \\bf 0.77 & 0.79 & 0.79 & 0.68 \\\\\nRoberta & \\bf 0.76 & 0.75 & \\bf 0.76 & 0.76 & 0.78 & 0.69 \\\\\nGermanBERT & 0.73 & 0.73 & \\bf 0.74 & 0.77 & 0.75 & 0.62 \\\\\nGBERT & \\bf 0.74 & 0.73 & 0.73 & 0.77 & 0.75 & 0.63 \\\\\nDistilbert & 0.65 & \\bf 0.67 & 0.66 & 0.63 & 0.73 & 0.59 \\\\\nhmBERT-mini & 0.63 & \\bf 0.67 & 0.65 & 0.66 & 0.72 & 0.53 \\\\\nhmBERT-tiny & 0.50 & 0.55 & \\bf 0.58 & 0.57 & 0.64 & 0.44 \\\\\n\\multicolumn{7}{c}{Europeana-ÖNB} \\\\\nEurop-Electra & 0.84 & 0.86 & \\bf 0.88 & 0.82 & 0.94 & 0.44 \\\\\nXLM-Roberta & 0.84 & \\bf 0.88 & 0.86 & 0.85 & 0.92 & 0.13 \\\\\nhmBERT & 0.84 & \\bf 0.86 & \\bf 0.86 & 0.78 & 0.92 & 0.50 \\\\\nRoberta & 0.81 & 0.84 & \\bf 0.87 & 0.81 & 0.92 & 0.20 \\\\\nGBERT & 0.83 & \\bf 0.84 & 0.83 & 0.75 & 0.92 & 0.40 \\\\\nGermanBERT & 0.82 & 0.83 & \\bf 0.84 & 0.73 & 0.92 & 0.53 \\\\\nhmBERT-mini & 0.70 & 0.76 & \\bf 0.78 & 0.68 & 0.86 & 0.28 \\\\\nDistilbert & 0.70 & 0.74 & \\bf 0.75 & 0.61 & 0.86 & 0.15 \\\\\nhmBERT-tiny & 0.50 & 0.63 & \\bf 0.65 & 0.48 & 0.78 & 0.38 \\\\\n\\multicolumn{7}{c}{HIPE 2020} \\\\\nEurop-Electra & 0.76 & \\bf 0.78 & 0.75 & 0.75 & 0.84 & 0.57 \\\\\nGermanBERT & 0.73 & \\bf 0.76 & 0.74 & 0.75 & 0.81 & 0.60 \\\\\nhmBERT & 0.73 & \\bf 0.75 & \\bf 0.75 & 0.72 & 0.82 & 0.54 \\\\\nGBERT & \\bf 0.74 & \\bf 0.74 & \\bf 0.74 & 0.72 & 0.81 & 0.48 \\\\\nXLM-Roberta & 0.73 & \\bf 0.74 & \\bf 0.74 & 0.71 & 0.82 & 0.50 \\\\\nRoberta & 0.67 & \\bf 0.70 & \\bf 0.70 & 0.68 & 0.77 & 0.50 \\\\\nDistilbert & 0.60 & \\bf 0.62 & \\bf 0.62 & 0.52 & 0.74 & 0.33 \\\\\nhmBERT-mini & 0.57 & 0.58 & \\bf 0.62 & 0.50 & 0.74 & 0.38 \\\\\nhmBERT-tiny & 0.40 & 0.48 & \\bf 0.51 & 0.36 & 0.64 & 0.31 \\\\\n\\multicolumn{7}{c}{Neiss-Arendt} \\\\\nGermanBERT & \\bf 0.88 & \\bf 0.88 & \\bf 0.88 & 0.94 & 0.83 & 0.74 \\\\\nhmBERT & 0.87 & \\bf 0.88 & 0.87 & 0.94 & 0.85 & 0.71 \\\\\nGBERT & 0.87 & 0.87 & \\bf 0.88 & 0.95 & 0.81 & 0.71 \\\\\nRoberta & 0.86 & \\bf 0.87 & \\bf 0.87 & 0.92 & 0.83 & 0.72 \\\\\nDistilbert & 0.85 & \\bf 0.87 & \\bf 0.87 & 0.92 & 0.80 & 0.72 \\\\\nXLM-Roberta & 0.86 & 0.86 & \\bf 0.87 & 0.93 & 0.85 & 0.69 \\\\\nEurop-Electra & \\bf 0.86 & \\bf 0.86 & \\bf 0.86 & 0.93 & 0.80 & 0.75 \\\\\nhmBERT-mini & 0.85 & \\bf 0.86 & 0.84 & 0.91 & 0.84 & 0.70 \\\\\nhmBERT-tiny & 0.79 & \\bf 0.83 & \\bf 0.83 & 0.89 & 0.82 & 0.64 \\\\\n\\multicolumn{7}{c}{Neiss-Sturm} \\\\\nXLM-Roberta & 0.90 & \\bf 0.93 & \\bf 0.93 & 0.95 & 0.88 & - \\\\\nhmBERT & \\bf 0.91 & \\bf 0.91 & \\bf 0.91 & 0.94 & 0.83 & - \\\\\nEurop-Electra & 0.89 & \\bf 0.92 & \\bf 0.92 & 0.92 & 0.90 & - \\\\\nGermanBERT & \\bf 0.91 & \\bf 0.91 & 0.90 & 0.93 & 0.86 & - \\\\\nGBERT & 0.89 & \\bf 0.91 & \\bf 0.91 & 0.95 & 0.84 & - \\\\\nRoberta & 0.88 & \\bf 0.91 & \\bf 0.91 & 0.95 & 0.86 & - \\\\\nDistilbert & 0.85 & 0.88 & \\bf 0.90 & 0.92 & 0.86 & - \\\\\nhmBERT-mini & 0.82 & \\bf 0.86 & \\bf 0.86 & 0.90 & 0.79 & - \\\\\nhmBERT-tiny & 0.71 & 0.75 & \\bf 0.78 & 0.79 & 0.74 & - \\\\\n\\bottomrule\n\\end{tabular}\n'